I-TECH-UW/OpenELIS-Global-2

src/main/java/org/openelisglobal/testconfiguration/controller/TestCatalogController.java

Error might be introduced by another part of the code, but this fix will at least stop the error from occurring

bugfix #177406155 error thrown when no active testresult found

---

src/main/java/org/openelisglobal/dataexchange/fhir/service/FhirTransformServiceImpl.java

Add multiple DiagnosticResources resources to task.outpt belongig to the same refering task

add multiple DR to task.output

---

src/main/java/org/openelisglobal/common/rest/provider/PatientSearchRestController.java

This PR addresses couple of bugs in [patient search form](https://openelis28.openelis-global.org/PatientManagement)
1. When all the fields are left empty and the form is submitted, it gets stuck in loading screen.
2. When the form is submitted with an invalid Previous Lab Number, the form gets stuck in loading screen.

Fix bugs in patient search form

---

frontend/src/components/addOrder/AddOrder.js

The `Search Site Name` is a required field in the Add Order page as mentioned in https://github.com/I-TECH-UW/OpenELIS-Global-2/issues/592 but lacks a required field indicator(red asterisk). This PR aims to implement the necessary changes.

Add required field indicator to site name in Add Order page

---

.github/workflows/label-merge-conflict.yml

Description:
Fixes : #745 
This pull request proposes the implementation of automation to enhance our code review process by automatically detecting merge conflicts and notifying authors promptly. Currently, identifying merge conflicts during code review poses a challenge, often leading to delays and inefficiencies.
With this automation, when a merge conflict occurs, a label will be applied to the pull request, and a comment will be posted, specifically mentioning the author. This notification will advise the author to rebase their branch against the base branch to resolve the conflict efficiently. By implementing this solution, we aim to streamline our code review process and ensure smoother collaboration among team members.
Images for pr after detecting Conflicts

Automated Merge Conflict Detection and Notification

---

.github/workflows/label-merge-conflict.yml

This pull request removes an unnecessary slash in the GitHub repository name, which is causing the workflow to auto-label merge conflicts  skipping and prevents it from running.
Expected Behaviour:
But now:

Fixed Auto label Merge Conflict Workflow

---

frontend/src/components/validation/Validation.js

This pull request addresses the alignment responsiveness issue reported in GitHub issue #825 . The checkboxes within the validation component were not aligning properly on smaller screens, leading to inconsistency and potential usability issues. 
Before:
After:
Thank You

Implement Responsive Checkbox Alignment in Validation Component

---

frontend/src/components/printBarcode/ExistingOrder.js
frontend/src/components/printBarcode/Index.js
frontend/src/components/printBarcode/PrePrint.js

This pull request addresses the responsiveness issue identified in the GitHub issue #811 . The print barcode page's layout becomes distorted and cluttered when the viewport width is less than 1056 pixels, impacting user readability and usability. To resolve this issue, the following changes have been implemented:
Improved responsiveness of the print barcode page, ensuring that elements are correctly displayed and spaced for viewport widths less than 1086 pixels.
Enhanced readability, usability, and overall user satisfaction with the feature.
Before:
After:
Thank You

Fix Distorted Responsiveness on Print Barcode Page

---

frontend/src/components/home/Dashboard.css

This pull request addresses the responsiveness issues #804  observed in the home dashboard tiles, particularly on smaller screens. 
Before:
After:
Thank you

Improve Responsiveness of Individual Home Dashboard Tiles

---

src/main/java/org/openelisglobal/common/rest/provider/PatientDashBoardProvider.java

Fixes #767 
**Issue:** The `calculateAverageReceptionToValidationTime`, `calculateAverageReceptionToResultTime`, `calculateAverageResultToValidationTime` method was returning NaN due to division by zero when the hours list was empty.
**Fix:** Added a check to ensure that the hours list is not empty before performing the division. If the hours list is empty, the method now returns 0.0 instead.
<br/>
<hr/>
<br/>
<hr/>
<br/>
<br/>
<hr/>
<br/>
<hr/>
cc @mozzy11

fixed average turn around time tile returning NaN

---

frontend/src/components/admin/menu/BillingMenuManagement.js

This pull request addresses the issue #776 : "Ensure Submit Button Clicks Only with Valid Billing URL Input." 
- Implemented client-side validation to ensure that the submit button is clickable only when a valid billing URL is entered into the input box.
- Added validation logic to check for a valid URL format before enabling the submit button.
- Updated the UI to display error messages when an invalid URL format is detected.
- Tested the changes locally by inputting various billing URLs.
- Ensured that the submit button remained disabled until a valid URL was entered.
- Verified that appropriate error messages were displayed for invalid URL formats.
Before: 
After:
This PR is ready to review
Thank you

Implement Client-Side Validation for Billing Menu Management

---

frontend/src/components/Style.css

Previously, the input fields on the Patient History and Add/Edit Patient pages were overflowing because two fields were arranged in a single row, leading to responsiveness issues on mobile view. To address this, each page now accommodates one input field per row for mobile view, ensuring responsiveness .
Mobile View
Desktop View
Mobile View
Desktop View

Fixed Responsiveness of Patient History and Add/Edit Patient Page

---

frontend/src/components/Style.css

This PR resolves the issue of underflow of admin Page content under side Navbar on Program Entry Page of Admin section in mobile view.

Fixed underflow of adminPageContent under Side Navbar

---

frontend/src/components/admin/menu/NonConformityMenuManagement.js
frontend/src/components/admin/menu/PatientMenuManagement.js
frontend/src/components/admin/menu/StudyMenuManagement.js

Previously, the Non-Conformity Menu Management, Patient Menu Management and Study Menu Management pages did not feature breadcrumbs. This pull request addresses this by adding breadcrumbs, thus improving user navigation.

Included Breadcrumbs to Non-Conformity Menu Management, Patient Menu Management and Study Menu Management pages

---

frontend/src/components/admin/menu/BillingMenuManagement.js
frontend/src/components/admin/menu/GlobalMenuManagement.js

Previously, the Billing Menu Management and Global Menu Management pages did not feature breadcrumbs. This pull request addresses this by adding breadcrumbs, thus improving user navigation.

Implemented Breadcrumbs to Billing Menu Management and Global Menu Management

---

frontend/src/components/admin/labNumber/LabNumberManagement.js
frontend/src/components/admin/program/ProgramManagement.js

Previously, the  Lab Number Management and Program Entry pages did not feature breadcrumbs. This pull request addresses this by adding breadcrumbs, thus improving user navigation.

Embedded Breadcrumbs to Lab Number Management and Program Entry Pages

---

frontend/src/components/admin/calculatedValue/CalculatedValueForm.tsx
frontend/src/components/admin/reflexTests/ReflexTestManagement.js

Previously, the Calculated Value Test and Reflex Test Management pages did not feature breadcrumbs. This pull request addresses this by adding breadcrumbs, thus improving user navigation.

Added Breadcrumbs to Calculated Value Test and Reflex Test Management pages

---

frontend/src/components/workplan/PanelSelectForm.js
frontend/src/components/workplan/PrioritySelectForm.js
frontend/src/components/workplan/TestSectionSelectForm.js
frontend/src/languages/en.json
frontend/src/languages/fr.json

Previously, there was a select box on the workplan pages. The first option in this select box on all these pages was set to 'null' instead of displaying helpful placeholder text. This PR improves the user experience by adding placeholder text in the work plan dropdowns. For instance, phrases like 'Select Panel Type,' 'Select Unit Type,' and 'Select Priority' have been added on the Workplan by Panel page, Workplan by Unit page, and Workplan by Priority page respectively.
This PR fixes the issue https://github.com/I-TECH-UW/OpenELIS-Global-2/issues/874
https://github.com/I-TECH-UW/OpenELIS-Global-2/assets/146843890/2a21b2d4-60f8-4a52-a22c-1cc5eb8f4e11
https://github.com/I-TECH-UW/OpenELIS-Global-2/assets/146843890/547f083b-17b4-4e96-8ada-fa6d209f7265
And, I also implemented support for …

Adding Placeholder Text in Workplan Dropdowns (On Workplan by Panel, Priority & Unit Pages)

---

frontend/src/components/Style.css
frontend/src/components/layout/Header.js

This PR makes sure that the "Open ELIS" and "Logout" texts in the HeaderPanel line up correctly with the icons on the left. It also improves interface usability by adjusting the HeaderPanel width to prevent it from covering most of the screen on smaller devices.
This PR fixes the issue https://github.com/I-TECH-UW/OpenELIS-Global-2/issues/871
https://github.com/I-TECH-UW/OpenELIS-Global-2/assets/146843890/73e77704-c860-4fe8-b28d-4aedff70eb1e
https://github.com/I-TECH-UW/OpenELIS-Global-2/assets/146843890/b5360801-c9e5-4193-8451-9ad37902411c

Fixing HeaderPanel Alignment and Screen Coverage Issue

---

frontend/src/components/admin/reflexTests/ReflexRuleForm.js

Previously, the Reflex Tests Management Page under admin section was not responsive for small screen sizes. 
This PR makes the Reflex Tests Management Page fully responsive for all screen sizes.
[Screencast from 23-03-24 12:17:00 AM IST.webm](https://github.com/I-TECH-UW/OpenELIS-Global-2/assets/96368921/6059373b-7a15-4f5c-bdf6-c3a406337a05)
[Screencast from 23-03-24 12:14:59 AM IST.webm](https://github.com/I-TECH-UW/OpenELIS-Global-2/assets/96368921/f2456d19-656b-44a2-81cb-5e73ee6b40fc)

Improved Responsiveness of Reflex Tests Management Page

---

frontend/src/components/home/Dashboard.tsx
src/main/java/org/openelisglobal/common/provider/query/PatientDashBoardForm.java
src/main/java/org/openelisglobal/common/rest/provider/PatientDashBoardProvider.java
src/main/java/org/openelisglobal/common/rest/util/PatientDashBoardPaging.java

Added API pagination logic into Orders controller & Integrated Home Dashboard with API pagination functionality.
Before, all the data would go to the Frontend and would be paginated there only, now the data gets paginated by the API(100 results per bundle) and is sent in chunks/bundles to the Frontend for further pagination by the Frontend(i.e into 10, 20, 30, 50 or 100 results per page).
**Before**
https://github.com/I-TECH-UW/OpenELIS-Global-2/assets/96483874/5908a08e-a072-495e-8add-eac823122928
**After**
To test the pagination, property `org.openelisglobal.paging.results.pageSize:2` was set to 2(i.e. 3 results per page), this test is shown below along with enabled/disabled Next and Previous Bundle buttons.
https://github.com/I-TECH-UW/OpenELIS-Global-2/assets/96483874/70e8678d-2403-474e …

Adding API pagination to the Dashboard Order Lists #681

---

frontend/src/components/home/Dashboard.css

This PR addresses the issue #887 
Subsequently, this PR addresses the responsiveness of overflow of home dashboard tiles for all screen width devices
Before: iPad view
After: iPad View

Fixed home-dashboard responsiveness

---

frontend/src/components/common/PatientHeader.js
frontend/src/components/pathology/PathologyCaseView.js

This PR fixes the issue #892 . Subsequently it addresses the patient header responsiveness to all the components where it has been reused like in following components:
->Pathology dashboard
->Immunohistochemistry Dashboard
->Cytology dashboard
->Modify order components
Before -->Pathology dashboard:iPad view
After:iPad view
Before:Modify order component: iPad view
After:Modify order component: iPad view
@mozzy11 This PR is ready to review, and would like for your valuable feedback on this PR.
Thank you

Fixed responsiveness for patient header

---

frontend/src/components/Style.css

This pull request addresses the issue #900  where the header panel component pops up automatically at a maximum width of 375px without user interaction. Additionally, it resolves the problem where clicking on the cancel (X) button fails to close the panel as expected.
Before:
[Screencast from 26-03-24 11:15:13 AM IST.webm](https://github.com/I-TECH-UW/OpenELIS-Global-2/assets/106299466/ab3313d8-df23-4fc9-90de-5d3a10ca283f)
After:
[After.webm](https://github.com/I-TECH-UW/OpenELIS-Global-2/assets/106299466/2ddcf14d-937e-44f2-94d4-b459b56230f3)
@mozzy11 This PR is ready for review. Please review the changes and provide your valuable feedback.
Thank you

Fixed Header panel Component Popup Behavior

---

frontend/src/components/cytology/CytologyCaseView.js
frontend/src/components/immunohistochemistry/ImmunohistochemistryCaseView.js

This PR fixes the issue #910 . Subsequently it addresses the specimen details responsiveness to the components below the patient header in Immunohistochemistry dashboard
Before:iPad view(width:810 px)
After:
@mozzy11 Sir, This PR is ready to review
Thank you

Fixed patient header in Cytology and Immunohistochemistry dashboard

---

frontend/src/components/pathology/PathologyCaseView.js

This PR addresses the issue #914 
1. Aligned various selectors in the pathology‬‭ dashboard adequately‬ for smaller screens.‬
Before: iPad view (width:810 px)
After:
2. Align, the checkbox "Refer to Immunohistochemistry" selectors appropriately.
Before:
After:
3. Aligned various Textarea input boxes‬:
Before:
After:
@mozzy11 Sir, This PR is ready to review, I would appreciate for your valuable feedback.
Thank you.

Fixed pathology dashboard selectors alignment

---

frontend/src/components/home/Dashboard.tsx

This PR addresses the issue #940 
Before: iPad view
After:
Before: Phone view
After:
@mozzy11 Sir, This PR is ready to review.
Thank you!

Fixed home dashboard tabs responsiveness

---

frontend/src/components/layout/Header.js

These have been persistent in the browser console and i felt we should fix that

Fix the browser console style errors due to bad syntax

---

src/main/java/org/openelisglobal/testcalculated/action/util/TestCalculatedUtil.java
src/main/java/org/openelisglobal/testreflex/action/util/TestReflexUtil.java

Fix Rule Builder

---

src/main/java/org/openelisglobal/hibernate/search/analysis/CustomLuceneAnalysisConfigurer.java
src/main/java/org/openelisglobal/patient/valueholder/Patient.java
src/main/java/org/openelisglobal/person/valueholder/Person.java
src/main/resources/persistence/persistence.xml
src/test/resources/persistence/test-persistence.xml

Issue - https://github.com/I-TECH-UW/OpenELIS-Global-2/issues/1049
- We will use `@Indexed` and `@*Field` (such as `@KeywordField`) annotations to map _Patient_ and _Person_ entities and their fields to Lucene indexes.
- We will create a custom _normalizer_ that includes _lowercase_ and _ascii-folding_ filters for the _Keyword_ fields. These filters will convert every character to lowercase and replace characters with diacritics ("é", "à", …​) with their ASCII equivalent ("e", "a", …​).

Add mapping for indexing Patient and Person entities

---

frontend/src/components/admin/Admin.js
frontend/src/components/admin/ResultReportingConfiguration/ResultReportingConfiguration.js
frontend/src/languages/en.json
frontend/src/languages/fr.json
src/main/java/org/openelisglobal/resultreporting/controller/rest/ResultReportingConfigurationRestController.java

documentation.
- created Rest Controller
- created React Js page
- enabled page in ADMIN.JS

fix: JSP page Result Reporting Configuration to React Js

---

src/test/resources/persistence/test-persistence.xml

Issue - https://github.com/I-TECH-UW/OpenELIS-Global-2/issues/1049
- We will use `local-heap` directory type in the testing configuration to store indexes in the local JVM’s heap instead of the default `local-filesystem`.
- This will be different from the main configuration where we use `local-filesystem` directory type to [implement persistent Lucene indexing with Docker volumes](https://github.com/I-TECH-UW/OpenELIS-Global-2/pull/1064).
- [Reference documentation](https://docs.jboss.org/hibernate/search/6.1/reference/en-US/html_single/#backend-lucene-configuration-directory-local-heap)
CC: @mozzy11

Change index directory type to local heap in testing configuration

---

frontend/src/components/admin/Admin.js
frontend/src/languages/en.json
frontend/src/languages/fr.json

- referencing #1051 
- https://localhost/api/OpenELIS-Global/NonConformityConfigurationMenu
- https://localhost/api/OpenELIS-Global/MenuStatementConfigMenu
If any changes required please let me know : )
Thank You

Added left-over pages routes of admin menuConfigs

---

src/main/java/org/openelisglobal/image/controller/DBImageController.java

Fix: Remove unnecessary @ResponseBody annotation from DBImageController
Fixes #1196
This pull request removes the redundant @ResponseBody annotation from the getImage method in the DBImageController class. The @RestController annotation already includes @ResponseBody functionality, making the explicit use of @ResponseBody unnecessary.

remove unnecessary ResponseBody annotation

---

src/main/java/org/openelisglobal/reports/action/implementation/PatientCILNSPClinical_vreduit.java
src/main/java/org/openelisglobal/reports/action/implementation/PatientReport.java

patient report should only return validated tests with onlyresults

---

docker-compose.yml
frontend/cypress/e2e/dashboard.cy.js
frontend/src/components/admin/reflexTests/ReflexStyles.css
frontend/src/components/common/AutoComplete.js

minor fixes
