I-TECH-UW/OpenELIS-Global-2

- liquibase/OE-In/nc_event.xml
- liquibase/OE-In/nce_action_log.xml
- liquibase/OE-In/nce_category.xml
- liquibase/OE-In/nce_specimen.xml
- liquibase/OE-In/nce_type.xml
- liquibase/OE-In/report.xml
- src/main/java/org/openelisglobal/reportconfiguration/daoimpl/ReportDAOImpl.java
- src/main/resources/languages/message_en.properties
- src/main/resources/languages/message_fr.properties
- src/main/webapp/META-INF/context.xml
- src/main/webapp/WEB-INF/web.xml
- src/main/webapp/pages/reportconfiguration/reportConfiguration.jsp
This PR contained the following fixes
- restored security constraints in web.xml
- Removed merge conflict tags
- Restored variable configuration in context.xml
- Fixed validation errors when creating a new report
- Fixed query to prevent sql injection
- Updated liquibase script to set owner of newly created sequence
> Fixed reported issues

- src/main/java/org/openelisglobal/dataexchange/fhir/service/TaskInterpreterImpl.java
> use uuid's

- pom.xml
- src/main/java/org/openelisglobal/common/provider/query/LabOrderSearchProvider.java
- src/main/java/org/openelisglobal/dataexchange/fhir/service/FhirApiWorkFlowServiceImpl.java
- src/main/java/org/openelisglobal/dataexchange/fhir/service/FhirApiWorkflowService.java
- src/main/java/org/openelisglobal/dataexchange/resultreporting/ResultReportingTransfer.java
- src/main/resources/adminPassword.txt
> getLocalFhirStorePath

- src/main/java/org/openelisglobal/dataexchange/fhir/service/FhirApiWorkFlowServiceImpl.java
- src/main/resources/adminPassword.txt
> work flow timer

- src/main/java/org/openelisglobal/dataexchange/resultreporting/ResultReportingTransfer.java
- src/main/resources/adminPassword.txt
remove extra task create, fix subject reference
> remove extra task create, fix subject reference

- src/main/java/org/openelisglobal/common/provider/query/LabOrderSearchProvider.java
- src/main/java/org/openelisglobal/dataexchange/fhir/service/FhirApiWorkFlowServiceImpl.java
- src/main/java/org/openelisglobal/dataexchange/fhir/service/TaskInterpreter.java
- src/main/java/org/openelisglobal/dataexchange/fhir/service/TaskInterpreterImpl.java
- src/main/java/org/openelisglobal/dataexchange/fhir/service/TaskWorker.java
- src/main/java/org/openelisglobal/dataexchange/resultreporting/ResultReportingTransfer.java
- src/main/resources/adminPassword.txt
Results in task output component referencing multiple diagnostic reports
each referencing single observations.
> Add support for multiple service requests per task.

- src/main/java/org/openelisglobal/common/provider/query/PatientSearchProvider.java
- src/main/java/org/openelisglobal/common/provider/query/workerObjects/PatientSearchLocalAndExternalWorker.java
- src/main/java/org/openelisglobal/common/provider/query/workerObjects/PatientSearchLocalWorker.java
- src/main/java/org/openelisglobal/common/provider/query/workerObjects/PatientSearchWorker.java
- src/main/java/org/openelisglobal/common/provider/validation/SubjectNumberValidationProvider.java
- src/main/java/org/openelisglobal/patient/action/bean/PatientEnhancedSearch.java
- src/main/java/org/openelisglobal/patient/controller/PatientManagementController.java
- src/main/java/org/openelisglobal/sample/controller/SampleEditController.java
- src/main/java/org/openelisglobal/sample/dao/SearchResultsDAO.java
- src/main/java/org/openelisglobal/sample/daoimpl/SearchResultsDAOImp.java
- src/main/java/org/openelisglobal/sample/form/SamplePatientEntryForm.java
- src/main/java/org/openelisglobal/sample/service/PatientManagementUpdate.java
- src/main/java/org/openelisglobal/search/service/SearchResultsService.java
- src/main/java/org/openelisglobal/search/service/SearchResultsServiceImpl.java
- src/main/resources/static/scripts/ajaxCalls.js
- src/main/resources/tiles/tiles-globalOpenELIS.xml
- src/main/webapp/pages/patient/patientEnhancedSearch.jsp
- src/main/webapp/pages/patient/patientManagement.jsp
- src/main/webapp/pages/patient/patientSearch.jsp
- src/main/webapp/pages/samplebatchentry/routine/patientManagement.jsp
- src/main/webapp/pages/samplebatchentry/routine/patientSearch.jsp
> Enhanced Patient Search

- .github/workflows/ci.yml
- .gitignore
- README.md
This is the inntial ci build pipeline ,this will build every Pr and can be triggered to run manually
> add innitial ci build pipeleine

- pom.xml
- src/main/java/org/openelisglobal/dataexchange/order/controller/ElectronicOrdersController.java
- src/main/java/org/openelisglobal/dataexchange/order/dao/ElectronicOrderDAO.java
- src/main/java/org/openelisglobal/dataexchange/order/daoimpl/ElectronicOrderDAOImpl.java
- src/main/java/org/openelisglobal/dataexchange/service/order/ElectronicOrderService.java
- src/main/java/org/openelisglobal/dataexchange/service/order/ElectronicOrderServiceImpl.java
> electronic order date search to timestamp

- pom.xml
- src/test/java/org/openelisglobal/BaseTestConfig.java
- src/test/java/org/openelisglobal/patient/PatientServiceTest.java
- src/test/java/org/openelisglobal/patient/PatientTestConfig.java
- src/test/java/org/openelisglobal/person/PersonServiceTest.java
- src/test/resources/hibernate/test-hibernate.cfg.xml
- src/test/resources/liquibase/base-test-changelog.xml
- src/test/resources/persistence/test-persistence.xml
- src/test/resources/postgre-db-init/postrgre_dump.sql.sql
I have tried to set up the actual Spring and HIbernate Context for the sample integration tests , and a little of mocking some some services.
Am also running this against the actual Postgress database managed by testContainers in order to have a testing enviroment that simulates the real runtime  enviroment
> Create Spring and Hibernate test Context for the intergration tests #283

- install/installerTemplate/linux/crosstab/crosstabCheck.sql
- install/installerTemplate/linux/setup_OpenELIS.py
> Fix crosstab installation check

- src/main/java/org/openelisglobal/result/controller/AnalyzerResultsController.java
PT story :https://www.pivotaltracker.com/story/show/181175738
> Fix Next/Previous button and partial fix for search on the Analyser Results Page

- install/installerTemplate/linux/initDB/OpenELIS-Global.sql
- src/main/java/org/openelisglobal/resultlimit/service/ResultLimitService.java
- src/main/java/org/openelisglobal/resultlimit/service/ResultLimitServiceImpl.java
- src/main/java/org/openelisglobal/resultlimits/valueholder/ResultLimit.java
- src/main/java/org/openelisglobal/testconfiguration/beans/ResultLimitBean.java
- src/main/java/org/openelisglobal/testconfiguration/controller/TestAddController.java
- src/main/java/org/openelisglobal/testconfiguration/controller/TestModifyEntryController.java
- src/main/java/org/openelisglobal/testconfiguration/validator/TestAddFormValidator.java
- src/main/java/org/openelisglobal/testconfiguration/validator/TestModifyEntryFormValidator.java
- src/main/resources/hibernate/hbm/ResultLimit.hbm.xml
- src/main/resources/languages/message_en.properties
- src/main/resources/languages/message_fr.properties
- src/main/resources/liquibase/2.4.x.x/reporting_range.xml
- src/main/webapp/pages/testConfiguration/testAdd.jsp
- src/main/webapp/pages/testConfiguration/testCatalog.jsp
- src/main/webapp/pages/testConfiguration/testModify.jsp
- src/test/resources/postgre-db-init/postrgre_dump.sql.sql
- volume/database/dbInit/OpenELIS-Global.sql
Implement "Reporting Range"
link:https://www.pivotaltracker.com/n/projects/18030/stories/179167495
> test:Implement Reporting Range

- src/main/java/org/openelisglobal/common/controller/BaseController.java
- src/main/java/org/openelisglobal/result/controller/AccessionResultsController.java
- src/main/java/org/openelisglobal/result/controller/LogbookResultsController.java
- src/main/java/org/openelisglobal/result/controller/PatientResultsController.java
- src/main/java/org/openelisglobal/result/controller/StatusResultsController.java
- src/main/java/org/openelisglobal/resultvalidation/controller/AccessionValidationController.java
- src/main/java/org/openelisglobal/resultvalidation/controller/AccessionValidationRangeController.java
- src/main/java/org/openelisglobal/resultvalidation/controller/ResultValidationController.java
- src/main/java/org/openelisglobal/systemuser/controller/UnifiedSystemUserController.java
- src/main/java/org/openelisglobal/systemuser/form/UnifiedSystemUserForm.java
- src/main/java/org/openelisglobal/systemuser/service/UserService.java
- src/main/java/org/openelisglobal/systemuser/service/UserServiceImpl.java
- src/main/java/org/openelisglobal/workplan/controller/WorkPlanByTestController.java
- src/main/java/org/openelisglobal/workplan/controller/WorkPlanByTestSectionController.java
- src/main/java/org/openelisglobal/workplan/controller/WorkplanByPanelController.java
- src/main/webapp/pages/systemuser/unifiedSystemUser.jsp
> Add ui functionality to dynamically add more Lab Unit Roles to user 

- src/main/webapp/pages/accessionvalidationrange/accessionValidationRange.jsp
- src/main/webapp/pages/resultvalidation/resultValidation.jsp
> Test Validation Screen

- dev/properties/common.properties
- src/main/java/org/openelisglobal/common/action/IActionConstants.java
- src/main/java/org/openelisglobal/organization/service/OrganizationImportServiceImpl.java
- src/main/java/org/openelisglobal/systemuser/controller/UnifiedSystemUserController.java
- src/main/java/org/openelisglobal/systemuser/form/UnifiedSystemUserForm.java
- src/main/resources/application.properties
- src/main/resources/languages/message_en.properties
- src/main/resources/languages/message_fr.properties
- src/main/webapp/pages/systemuser/unifiedSystemUser.jsp
- volume/properties/common.properties
> Add Ability to Copy roles from another User

- .github/workflows/ci.yml
- src/main/resources/languages/message_en.properties
- src/main/resources/languages/message_fr.properties
- src/main/webapp/pages/referral/referralOrderEntry.jsp
- src/main/webapp/pages/sample/sampleAdd.jsp
- src/main/webapp/pages/sample/sampleEdit.jsp
- src/main/webapp/pages/sample/samplePatientEntry.jsp
Refactor Order Entry page to dispay test per sample added
https://docs.google.com/document/d/1ixH5_MGXJI4TKj20g0ZQsB-393jbUy7N/edit
> Update order entry page

- src/main/java/org/openelisglobal/result/controller/AccessionResultsController.java
- src/main/java/org/openelisglobal/result/controller/LogbookResultsController.java
- src/main/java/org/openelisglobal/result/controller/PatientResultsController.java
- src/main/java/org/openelisglobal/result/controller/StatusResultsController.java
- src/main/java/org/openelisglobal/result/form/AccessionResultsForm.java
- src/main/java/org/openelisglobal/result/form/PatientResultsForm.java
- src/main/java/org/openelisglobal/result/form/StatusResultsForm.java
- src/main/webapp/pages/result/resultListView.jsp
> fix:adding methods to results by order and by patient

- src/main/java/org/openelisglobal/dataexchange/fhir/service/FhirTransformServiceImpl.java
> add all test results validated at ago as multiple output to the refering task Resource

- react-ui/src/components/addOrder/OrderReferralRequest.js
- react-ui/src/components/addOrder/SampleTypes.js
- react-ui/src/components/layout/Layout.js
- src/main/java/org/openelisglobal/common/rest/DisplayListController.java
- updates to the Order Entity React UI
> React order entry 002

- react-ui/src/components/addOrder/AddOrderTopForm.js
- react-ui/src/components/addOrder/AddSample.js
- react-ui/src/components/addOrder/CreateOrder.js
- react-ui/src/components/addOrder/Index.js
- react-ui/src/components/addOrder/OrderItemsTableRow.js
- react-ui/src/components/addOrder/OrderResultReporting.js
- react-ui/src/components/addOrder/SampleTypes.js
- react-ui/src/components/addOrder/add-order.scss
- react-ui/src/components/common/CreatePatientForm.js
- react-ui/src/components/common/SiteNameAutoComplete.js
- react-ui/src/components/data/SampleTypesTableHeaders.js
- react-ui/src/components/patient/PatientManagement.js
- src/main/java/org/openelisglobal/common/rest/DisplayListController.java
- src/main/java/org/openelisglobal/common/rest/provider/SampleEntryTestsForTypeProviderRestController.java
> Order Entry updates on sampleTypes section

- frontend/src/components/cytology/CytologyCaseView.js
- frontend/src/components/immunohistochemistry/ImmunohistochemistryCaseView.js
- frontend/src/components/pathology/PathologyCaseView.js
- frontend/src/languages/en.json
- frontend/src/languages/fr.json
- src/main/java/org/openelisglobal/common/services/DisplayListService.java
- src/main/java/org/openelisglobal/program/controller/pathology/PathologySampleForm.java
- src/main/java/org/openelisglobal/program/service/PathologyDisplayServiceImpl.java
- src/main/java/org/openelisglobal/program/service/PathologySampleServiceImpl.java
- src/main/java/org/openelisglobal/program/valueholder/pathology/PathologyCaseViewDisplayItem.java
- src/main/java/org/openelisglobal/program/valueholder/pathology/PathologyRequest.java
> update styling for programm case views and add status for patholgy reuests

- frontend/src/components/resultPage/SearchResultForm.js
Issue - https://github.com/I-TECH-UW/OpenELIS-Global-2/issues/654
> Add DatePicker to Results by test date page

- frontend/src/components/resultPage/SearchResultForm.js
- frontend/src/components/validation/SearchForm.js
Issue - https://github.com/I-TECH-UW/OpenELIS-Global-2/issues/613
> Add support for URL search params in Validation components

- frontend/src/components/resultPage/SearchResultForm.js
- frontend/src/components/workplan/PanelSelectForm.js
- frontend/src/components/workplan/PrioritySelectForm.js
- frontend/src/components/workplan/TestSectionSelectForm.js
- frontend/src/components/workplan/TestSelectForm.js
- frontend/src/components/workplan/WorkplanSearchForm.js
Issue - [WorkPlan component should support search Params via the URL #614](https://github.com/I-TECH-UW/OpenELIS-Global-2/issues/614)
> Add support for URL search params in WorkPlan components

- frontend/src/components/patient/SearchPatientForm.js
- frontend/src/components/resultPage/SearchResultForm.js
Issue - https://github.com/I-TECH-UW/OpenELIS-Global-2/issues/612
> Add support for URL search params in Result components

- src/main/java/org/openelisglobal/resultvalidation/controller/rest/AccessionValidationRestController.java
Fix crash of Validation Search by order on invalid input - https://github.com/I-TECH-UW/OpenELIS-Global-2/issues/674
> Fix validation by accession number API

- frontend/src/components/patient/SearchPatientForm.js
- src/main/java/org/openelisglobal/common/paging/PagingProperties.java
- src/main/java/org/openelisglobal/common/provider/query/PatientSearchResultsForm.java
- src/main/java/org/openelisglobal/common/rest/provider/PatientSearchRestController.java
- src/main/java/org/openelisglobal/common/rest/util/PatientSearchResultsPaging.java
Issue - https://github.com/I-TECH-UW/OpenELIS-Global-2/issues/680
> Add API pagination to Patient Search Results

- frontend/src/components/Style.css
This PR fixes the issue #732 
Before 
After
> Fixed overflow of text in navbar

- issue-template.md
Hi @mozzy11, as we discussed in the last dev call, there is a need for a template for issue reporting so that new contributors can easily report issues. I followed this format - https://github.com/I-TECH-UW/OpenELIS-Global-2/issues/192 with minor changes. Let me know if any other changes are required.
> Add issue-template.md

- README.md
Fixes #750 
During my setup of the project on my local PC, I encountered some issues due to the readability of the readme. This PR is to address some of those issues I found and improve the readme so that new contributors can easily set up the repo.
1) 
1) 
2)
> improve the readability of the README

- frontend/src/components/home/Dashboard.css
- frontend/src/components/home/Dashboard.tsx
> Fixed Responsiveness of home page

- frontend/src/components/Home.js
- frontend/src/components/Reports/Routine.js
- frontend/src/components/addOrder/Index.js
- frontend/src/components/common/HomeBreadCrumb.js
- frontend/src/components/common/PageBreadCrumb.js
- frontend/src/components/cytology/CytologyCaseView.js
- frontend/src/components/cytology/CytologyDashBoard.js
- frontend/src/components/eOrder/EOrderSearch.js
- frontend/src/components/immunohistochemistry/ImmunohistochemistryCaseView.js
- frontend/src/components/immunohistochemistry/ImmunohistochemistryDashboard.js
- frontend/src/components/modifyOrder/Index.js
- frontend/src/components/modifyOrder/ModifyOrder.js
- frontend/src/components/pathology/PathologyCaseView.js
- frontend/src/components/pathology/PathologyDashboard.js
- frontend/src/components/patient/PatientHistory.js
- frontend/src/components/patient/PatientManagement.js
- frontend/src/components/resultPage/ResultSearch.js
- frontend/src/components/validation/Index.js
- frontend/src/components/workplan/Workplan.js
This Pr adds a generic Breadcrumb component 
which makes code modular simpler removing unnecessary imports in place
> Generic Breadcrumb Component

- frontend/src/components/modifyOrder/SearchOrder.js
This PR fixes the issue #747  which involves improving overall Viewport Compatibility, Layout Adjustment across all devices of modify order page.  (on max-width <1056px),
Before:
After:
Thank you
> Fixed responsiveness of modify order page

- frontend/src/components/resultPage/ResultSearch.js
- frontend/src/components/resultPage/SearchResultForm.js
This pull request addresses the issue #817  regarding viewport compatibility and responsiveness on the status result page. The proposed changes aim to enhance user satisfaction and engagement by ensuring a consistent and user-friendly experience across all devices.
Before:
After:
>  Fixed Viewport Compatibility and Enhance Responsiveness on Status Result Page

- frontend/src/components/workplan/Workplan.js
- frontend/src/components/workplan/WorkplanSearchForm.js
This PR  improves the  overall responsiveness, Viewport Compatibility, Layout Adjustment across all devices of workplan page. (on max-width <1056px).
Steps to reproduce:
Go to nav items ->workplan ->By Test Type
Before:
After:
This PR is ready to review 
Thank you
> Fixed responsiveness of workplan

- .github/workflows/frontend-qa.yml
- frontend/cypress/e2e/patientEntry.cy.js
- frontend/cypress/pages/HomePage.js
- frontend/cypress/pages/OrderEntityPage.js
- frontend/cypress/pages/PatientEntryPage.js
- frontend/package.json
>Fixing Issue #787 
**Previously:**
**Currently:**
**>Recording Before:**
https://github.com/I-TECH-UW/OpenELIS-Global-2/assets/128405481/28f916db-c6f8-4618-85b0-ab62e48f236a
https://github.com/I-TECH-UW/OpenELIS-Global-2/assets/128405481/28d601f6-16fd-4ace-b14d-b46ad6b0845b
.
**>Recording After:**
https://github.com/I-TECH-UW/OpenELIS-Global-2/assets/128405481/1c916854-2912-4204-9c57-d57ffb098614
https://github.com/I-TECH-UW/OpenELIS-Global-2/assets/128405481/64b002d2-ad59-4a85-9354-b38edf0b0c1a
>  Fixing Failing Test Suites for Patient and Order Entities

- frontend/src/components/Reports/routine/HivTestSummary.js
- frontend/src/components/Reports/routine/PatientStatusReport.js
- frontend/src/components/Reports/routine/RejectionReport.js
- frontend/src/components/Reports/routine/StatisticsReport.js
- frontend/src/components/Reports/routine/SummaryOfAllTest.js
This is a followup commit caused by the commit -> https://github.com/I-TECH-UW/OpenELIS-Global-2/pull/783
[Screencast from 2024-03-19 11-43-02.webm](https://github.com/I-TECH-UW/OpenELIS-Global-2/assets/47120265/79b9d574-55a2-464c-abf3-d7781c008637)
[Screencast from 2024-03-19 12-46-06.webm](https://github.com/I-TECH-UW/OpenELIS-Global-2/assets/47120265/a8a51d3b-d6fe-47c6-97f7-62db56d0fd0c)
> Fix for Routine Reports caused by Referred Out Tests Recently Merged!

- frontend/src/components/modifyOrder/SearchOrder.js
This PR addresses the issue #842 
Before:(Tablet view)
After:(Tablet view)
Thank You
> Fixed Inconsistent display of the input filed in modify order form

- frontend/src/components/Style.css
This PR addresses the issue #837 
Before:
After:
@mozzy11 This PR is ready to review. Thank you!
> Fixed age/years improper stacking

- frontend/src/components/Style.css
Fixes #851 
Fixed responsiveness of the programs page on smaller devices
> fix responsiveness on programs admin page

- frontend/src/components/Style.css
- frontend/src/components/layout/Header.js
> Making Navbar Responsive for Small Devices

- frontend/src/components/admin/menu/CommonProperties.js
- volume/properties/common.properties
> Update App proprties Config

- frontend/src/components/printBarcode/Index.js
This PR adds Breadcrumbs to the Bar Code page for easy user navigation.
Resolves Issue #907
> Added Breadcrumbs to Bar Code page

- .gitpod.yml
- README.md
> update gitpod config

- volume/properties/common.properties
> remove default providerlist fhirstore

- frontend/src/components/home/Dashboard.tsx
- frontend/src/languages/en.json
- frontend/src/languages/fr.json
> fix Tab error

- .github/workflows/frontend-qa.yml
- frontend/cypress.config.js
> Cypress github Action updates

- frontend/.gitignore
- frontend/cypress.config.js
- frontend/cypress/common/TestProperties.js
- frontend/cypress/e2e/login.cy.js
- frontend/cypress/e2e/modifyOrder.cy.js
- frontend/cypress/e2e/orderEntity.cy.js
- frontend/cypress/e2e/patientEntry.cy.js
- frontend/cypress/fixtures/Order.json
- frontend/cypress/fixtures/Patient.json
- frontend/cypress/pages/HomePage.js
- frontend/cypress/pages/ModifyOrderPage.js
- frontend/cypress/pages/OrderEntityPage.js
>**Solving issue #948**
**Recording**
https://github.com/I-TECH-UW/OpenELIS-Global-2/assets/128405481/d669c231-f55a-41a8-a1f8-f87f4c4c68df
> Test Coverage: Modify Order Page

- frontend/src/components/reports/Study.js
- frontend/src/components/reports/routine/PatientStatusReport.js
- frontend/src/components/reports/routine/ReferredOut.js
- frontend/src/components/reports/study/common/GenericReport.js
- frontend/src/components/reports/study/common/ReportByDate.js
- frontend/src/components/reports/study/common/ReportByDateCSV.js
- frontend/src/components/reports/study/index.js
- frontend/src/components/utils/Utils.js
- frontend/src/languages/en.json
- frontend/src/languages/fr.json
- src/main/java/org/openelisglobal/common/rest/DisplayListController.java
- src/main/java/org/openelisglobal/reports/action/implementation/ExportTrendsByDate.java
https://github.com/I-TECH-UW/OpenELIS-Global-2/assets/101407963/90675b48-6de9-4f05-a756-33bd4af4cb0f
fixes : #895 
This pr adds new page for of study reports: Export by Date Report and moved encodeDate function into utils
> Re-write Export by Date Report

- frontend/src/components/reports/routine/PatientStatusReport.js
- frontend/src/components/reports/study/common/GenericReport.js
- frontend/src/components/reports/study/common/ReportByDate.js
- frontend/src/components/reports/study/common/ReportByID.js
- frontend/src/components/reports/study/common/ReportByLabNo.js
- frontend/src/components/reports/study/index.js
This PR addresses the issue #961 . To improve responsiveness of all reports components across all devices.
Before: Phone view: width: 412px
After: Phone view: width: 412px
Before: Phone view: width: 412px
After: Phone view: width: 412px
Before: Phone view: width: 412px
After: Phone view: width: 412px
Similarly this has fixed responsiveness to all other reports components.
@mozzy11 Sir, this PR is ready to review.
Thank You!
> Fixed responsiveness of all reports components

- frontend/cypress/e2e/login.cy.js
- frontend/cypress/pages/LoginPage.js
**>Performed QA workflow runs 10-15 times to ensure it does not fail.** 
Here is the attached screenshot
> Fix Login E2E Tests

- frontend/src/components/immunohistochemistry/ImmunohistochemistryCaseView.js
> fix layout

- frontend/src/components/admin/menu/CommonProperties.js
This PR fixes the alignment and overall responsiveness of [admin/application properties](https://localhost/MasterListsPage#commonproperties) component across all screen sizes.
Before: iPad view width(810 px)
After: iPad view
Before: Phone view, width(412 px)
After: Phone view
@mozzy11 Sir, This PR is ready to review. I would appreciate for your valuable feedback.
Thank you!
> Fixed responsiveness of application properties component

- frontend/src/components/addOrder/AddOrder.js
- frontend/src/components/addOrder/Index.js
- frontend/src/components/admin/reflexTests/ReflexStyles.css
- frontend/src/components/modifyOrder/ModifyOrder.js
- src/main/java/org/openelisglobal/common/services/SampleOrderService.java
- src/main/java/org/openelisglobal/sample/controller/rest/SampleEditRestController.java
- src/main/java/org/openelisglobal/sample/service/SampleEditServiceImpl.java
> Requester and Provider should be editable on Modify order 

- frontend/src/components/modifyOrder/ModifyOrder.js
> fix sitename changing in the background

- frontend/src/components/reports/common/ReportByDate.js
- frontend/src/components/reports/common/ReportByDateCSV.js
This PR addresses the responsiveness issues in Routine reports/Activity report and Study reports/Export by date components.
Before: iPad view (width-810px)
After: iPad view (width-810px)
Before: iPad view (width-810px)
After: iPad view (width-810px)
Before: iPad view (width-810px)
After: iPad view (width-810px)
@mozzy11 Sir, this PR is ready to review, looking forward for your valuable feedback.
Thank you!
> Fixed routine reports components responsiveness

- frontend/cypress/pages/PatientEntryPage.js
- frontend/src/App.js
- frontend/src/components/reports/Index.js
- frontend/src/components/reports/Routine.js
- frontend/src/components/reports/Study.js
- frontend/src/components/reports/auditTrailReport/Index.js
- frontend/src/components/reports/common/PatientStatusReport.js
- frontend/src/components/reports/common/ReportByDate.js
- frontend/src/components/reports/common/ReportByDateCSV.js
- frontend/src/components/reports/common/ReportByID.js
- frontend/src/components/reports/common/ReportByLabNo.js
- frontend/src/components/reports/routine/Index.js
- frontend/src/components/reports/routine/ReferredOut.js
- frontend/src/components/reports/routine/StatisticsReport.js
- frontend/src/components/reports/study/IntermediateByService.js
- frontend/src/components/reports/study/NonConformityNotification.js
- frontend/src/components/reports/study/index.js
- src/main/java/org/openelisglobal/analysis/daoimpl/AnalysisDAOImpl.java
- src/main/java/org/openelisglobal/common/util/DateUtil.java
- src/main/java/org/openelisglobal/reports/action/implementation/ReportImplementationFactory.java
- src/main/java/org/openelisglobal/reports/controller/ReportController.java
> Update and Fix Breaking reports

- frontend/src/components/printBarcode/PrePrint.js
- frontend/src/languages/en.json
- frontend/src/languages/fr.json
> improve barcode print

- frontend/src/components/patient/SearchPatientForm.js
- src/main/java/org/openelisglobal/documentation/controller/DocumentationController.java
> Update User Manual Documentation

- pom.xml
- src/main/java/org/openelisglobal/analyzerimport/action/AnalyzerImportController.java
> fix astm analyzer receiver

- frontend/src/components/modifyOrder/SearchOrder.js
- frontend/src/components/patient/PatientHistory.js
- frontend/src/components/patient/PatientManagement.js
- frontend/src/components/patient/SearchPatientForm.js
- frontend/src/components/resultPage/SearchResultForm.js
> improve styling for patient search

- docs/gsoc.md
> update GSOC doc

- frontend/src/components/patient/CreatePatientForm.js
- src/main/java/org/openelisglobal/patient/controller/PatientManagementController.java
- src/main/java/org/openelisglobal/patient/controller/rest/PatientManagementRestController.java
- src/main/java/org/openelisglobal/patient/validator/ValidatePatientInfo.java
- src/main/java/org/openelisglobal/sample/daoimpl/SearchResultsDAOImp.java
- src/main/java/org/openelisglobal/sample/service/PatientManagementUpdate.java
> Fix Patient ID validation

- frontend/src/components/resultPage/SearchResultForm.js
- frontend/src/components/validation/Validation.js
> test name should display properly on result entry

- src/main/java/org/openelisglobal/result/controller/rest/LogbookResultsRestController.java
> fix  duplicate note creation error on results modification

- src/main/java/org/openelisglobal/resultvalidation/controller/rest/AccessionValidationRestController.java
> fix duplicate note on validation

- frontend/src/components/formModel/innitialValues/SearchPatientFormValues.js
- frontend/src/components/patient/SearchPatientForm.js
- src/main/java/org/openelisglobal/common/provider/query/workerObjects/PatientSearchLocalAndExternalWorker.java
- src/main/java/org/openelisglobal/common/provider/query/workerObjects/PatientSearchLocalWorker.java
- src/main/java/org/openelisglobal/common/provider/query/workerObjects/PatientSearchWorker.java
- src/main/java/org/openelisglobal/common/rest/provider/PatientSearchRestController.java
> add support for external patient search

- frontend/src/components/addOrder/Index.js
- frontend/src/components/common/CustomDatePicker.js
- frontend/src/components/common/CustomNotification.js
- frontend/src/components/formModel/innitialValues/SearchPatientFormValues.js
- frontend/src/components/patient/CreatePatientForm.js
- frontend/src/components/patient/SearchPatientForm.js
- src/main/java/org/openelisglobal/common/rest/DisplayListController.java
> minor fixes

- frontend/src/components/admin/menu/CommonProperties.js
> fix application proprties styling

- src/main/java/org/openelisglobal/common/rest/DisplayListController.java
- src/main/java/org/openelisglobal/dictionary/controller/rest/DictionaryMenuRestController.java
- src/main/java/org/openelisglobal/menu/form/AdminMenuForm.java
> innitial implementation of pagination for admin menu

- src/main/java/org/openelisglobal/provider/controller/rest/ProviderMenuRestController.java
- src/main/java/org/openelisglobal/provider/controller/rest/ProviderRestController.java
> implement pagination for provider menu API

- frontend/src/components/admin/barcodeConfiguration/BarcodeConfiguration.js
[Screencast from 2024-06-07 09-46-44.webm](https://github.com/I-TECH-UW/OpenELIS-Global-2/assets/47120265/36656220-7ba8-4cb4-8e1c-67f1d2d02bec)
[Screencast from 2024-06-07 09-46-05.webm](https://github.com/I-TECH-UW/OpenELIS-Global-2/assets/47120265/4a7917b0-5372-4e08-96c2-e934a45ed51a)
> Fix Barcode configuration to use orderLegendBody in a div

- frontend/src/components/admin/menu/DictionaryManagement.js
- src/main/java/org/openelisglobal/dictionary/controller/rest/DictionaryRestController.java
> Fix Modifying a dictionary menu item

- frontend/src/components/resultPage/SearchResultForm.js
> fix results responsivenes

- frontend/cypress/e2e/login.cy.js
- frontend/cypress/e2e/patientEntry.cy.js
- frontend/cypress/pages/ModifyOrderPage.js
- frontend/cypress/pages/PatientEntryPage.js
https://github.com/I-TECH-UW/OpenELIS-Global-2/assets/128405481/9c4653a9-2f01-4bb8-b78b-114140e8182d
> Fix E2E coverage for Patient Search

- frontend/src/components/admin/menu/DictionaryManagement.js
- src/main/java/org/openelisglobal/dictionary/controller/rest/DictionaryMenuRestController.java
- src/test/java/org/openelisglobal/dictionary/rest/controller/DictionaryMenuRestControllerTest.java
[Screencast from 2024-06-11 22-50-40.webm](https://github.com/I-TECH-UW/OpenELIS-Global-2/assets/47120265/c1a5ee59-4838-4bf7-b8ee-66798208b27f)
> Implement Search functionality of Dictionary Menu items

- src/main/java/org/openelisglobal/result/controller/rest/LogbookResultsRestController.java
- src/main/java/org/openelisglobal/testreflex/daoimpl/TestReflexDAOImpl.java
> fix Duplicate Error on Numeric Rules

- src/main/java/org/openelisglobal/common/rest/DisplayListController.java
- src/main/java/org/openelisglobal/testcalculated/action/util/TestCalculatedUtil.java
- src/main/java/org/openelisglobal/testreflex/action/util/TestReflexResolver.java
> debug other analyte

- src/main/java/org/openelisglobal/testreflex/action/util/TestReflexResolver.java
> fix Dictionary Rule

- frontend/src/App.js
- frontend/src/components/admin/Admin.js
- frontend/src/components/admin/OrganizationManagement/OrganizationAddModify.js
- frontend/src/components/admin/OrganizationManagement/OrganizationManagement.js
- frontend/src/components/utils/PathRoute.js
> Followup commit to fix Organization mgt

- frontend/src/components/admin/calculatedValue/CalculatedValueForm.tsx
- frontend/src/components/formModel/innitialValues/CalculatedValueFormSchema.tsx
- src/main/java/org/openelisglobal/testcalculated/action/util/TestCalculatedUtil.java
- src/main/java/org/openelisglobal/testcalculated/valueholder/Calculation.java
- src/main/resources/liquibase/2.8.x.x/calculated_value.xml
> add Note to calculated Results

- frontend/src/components/admin/OrganizationManagement/OrganizationManagement.js
> fig org Pagination buttons

- frontend/src/components/resultPage/SearchResultForm.js
- frontend/src/components/validation/Validation.js
> fix past Notes Display on results and Validation Page

- Dockerfile
- README.md
- pom.xml
> disbale formatter plugin by default

- README.md
- frontend/src/components/admin/calculatedValue/CalculatedValueForm.tsx
- pom.xml
- src/main/java/org/openelisglobal/testcalculated/action/util/TestCalculatedUtil.java
> Fix test Calculated

- frontend/src/components/admin/barcodeConfiguration/BarcodeConfiguration.js
> minor fix on Bar code config  componenet

- .github/workflows/ci.yml
- .github/workflows/frontend-qa.yml
- .github/workflows/publish-and-test.yml
- README.md
> minor cleanup

- frontend/src/components/admin/ProviderMenu/ProviderMenu.js
> fix provider Update

- .github/workflows/frontend-qa.yml
- .github/workflows/publish-and-test.yml
- Dockerfile
- Dockerfile.dev
> Further improve docker builds and add dev dockerfile to OpenELIS

- .github/workflows/publish-and-test.yml
> Add time lag before pulling test image

- frontend/cypress/.eslintrc.json
- frontend/src/components/admin/OrganizationManagement/OrganizationManagement.js
- frontend/src/components/resultPage/SearchResultForm.js
- frontend/src/languages/en.json
- frontend/src/languages/fr.json
- src/main/java/org/openelisglobal/dataexchange/fhir/service/FhirTransformService.java
- src/main/java/org/openelisglobal/dataexchange/fhir/service/FhirTransformServiceImpl.java
- src/main/java/org/openelisglobal/organization/controller/rest/OrganizationRestController.java
- src/main/java/org/openelisglobal/referral/fhir/service/FhirReferralServiceImpl.java
- src/main/java/org/openelisglobal/result/controller/rest/LogbookResultsRestController.java
> fix referal Results in React UI

- frontend/src/App.js
- frontend/src/components/common/CustomDatePicker.js
- frontend/src/components/resultPage/SearchResultForm.js
- frontend/src/languages/en.json
- frontend/src/languages/fr.json
> fix reffering multiple tests

- frontend/src/components/patient/resultsViewer/grouped-timeline/grouped-timeline.styles.scss
- frontend/src/components/patient/resultsViewer/grouped-timeline/grouped-timeline.tsx
> Add horizaotal scrol on patient results

- frontend/cypress/fixtures/Order.json
- frontend/cypress/fixtures/Patient.json
- frontend/cypress/pages/OrderEntityPage.js
- frontend/cypress/pages/PatientEntryPage.js
- frontend/src/components/resultPage/resultsReferredOut/ReferredOutTests.js
> fix Notes display on Refered tests

- frontend/src/components/resultPage/resultsReferredOut/ReferredOutTests.js
> fix referal label

- .gitignore
- frontend/src/components/reports/Routine.js
- frontend/src/components/reports/common/PatientStatusReport.js
- frontend/src/components/reports/common/ReportByDate.js
- frontend/src/components/reports/routine/Index.js
- frontend/src/components/resultPage/SearchResultForm.js
- src/main/java/org/openelisglobal/reports/controller/ReportController.java
- src/main/resources/liquibase/2.8.x.x/update_default_setting.xml
> update Routine Export report permision

- frontend/src/components/admin/calculatedValue/CalculatedValueForm.tsx
- frontend/src/components/admin/reflexTests/ReflexRuleForm.js
- src/main/java/org/openelisglobal/common/rest/DisplayListController.java
- src/main/java/org/openelisglobal/testcalculated/controller/rest/CalculatedValueRestController.java
- src/main/java/org/openelisglobal/testreflex/controller/rest/TestReflexRuleRestController.java
> imrpove loading rule meatadata

- frontend/src/components/admin/analyzerTestName/AnalyzerTestName.js
- src/main/java/org/openelisglobal/analyzerimport/controller/rest/AnalyzerTestNameRestController.java
https://github.com/I-TECH-UW/OpenELIS-Global-2/assets/128405481/2406059b-0317-4b23-bf85-6209939c6df8
> Analyzer Test Minor Fix

- pom.xml
- src/main/java/org/openelisglobal/common/util/StringUtil.java
- src/main/java/org/openelisglobal/result/controller/AnalyzerResultsController.java
> fix significant digits for recording analyzer results

- src/main/java/org/openelisglobal/person/valueholder/Person.java
- src/main/resources/hibernate/hbm/Person.hbm.xml
- src/test/java/org/openelisglobal/person/PersonServiceTest.java
> fix provider menu

- frontend/src/components/admin/userManagement/UserAddModify.js
- frontend/src/components/admin/userManagement/UserManagement.js
- AutoComplete for user Selection
> fix(userManagementPage): AutoComplete at Copy-UserPermission + debug cleanup

- frontend/src/components/admin/Admin.js
- frontend/src/components/admin/OrganizationManagement/OrganizationAddModify.js
- frontend/src/components/admin/userManagement/UserAddModify.js
> fix order of labunit roles on user page

- frontend/src/components/admin/OrganizationManagement/OrganizationAddModify.js
- frontend/src/components/admin/OrganizationManagement/OrganizationManagement.js
- frontend/src/components/admin/userManagement/UserAddModify.js
- frontend/src/components/admin/userManagement/UserManagement.js
> cleanup code

- frontend/src/components/admin/userManagement/UserAddModify.js
- refernce #1051 
- Conditional checking of boxes for "roleName === Global Adminstration"
> fix(userManagement): infinite rendering fix + conditional checkBox fixup

- frontend/cypress/fixtures/NonConform.json
- frontend/cypress/pages/HomePage.js
- frontend/cypress/pages/NonConformPage.js
- frontend/src/components/nonconform/common/ReportNonConformingEvent.jsx
- src/main/java/org/openelisglobal/common/provider/query/SampleEntryTestsForTypeProvider.java
- src/main/java/org/openelisglobal/qaevent/controller/rest/ReportNonConformEventsRestController.java
- src/main/java/org/openelisglobal/testconfiguration/controller/TestModifyEntryController.java
- src/main/java/org/openelisglobal/testconfiguration/service/TestModifyServiceImpl.java
> Modify test should modify orderable and active attributes

- frontend/src/components/patient/resultsViewer/results-viewer.tsx
> improve patient History page styling

- frontend/src/components/Style.css
> side nav links should be clickable

- .github/workflows/publish-and-test.yml
> update docker build cache

- frontend/src/components/layout/Header.js
>  fix  side nav item  when clicked

- frontend/src/components/admin/userManagement/UserAddModify.js
- removed initial validation on filed called ( password and confirmPassword ) 
- disabling save button on wrong input validation
> fix(userManagementValidation): minnor hot fix on userNanagment disable inital validation

- frontend/src/components/admin/userManagement/UserAddModify.js
- referencing #1051 
URL : https://oe3.openelis-global.org/MasterListsPage#userEdit?ID=0&startingRecNo=1&roleFilter=
> chore(userManagement): minnor hot fix 01 save button fix

- src/test/java/org/openelisglobal/patient/PatientServiceTest.java
documentation.
Add more integration tests to the Patient and Person service https://github.com/I-TECH-UW/OpenELIS-Global-2/issues/902
@mozzy11 kindly review !
> Add-more-Patient Test

- frontend/src/components/layout/Header.js
- frontend/src/components/layout/search/searchBar.css
- frontend/src/components/layout/search/searchBar.js
- frontend/src/components/layout/search/searchOutput.js
- frontend/src/components/layout/search/searchService.js
- src/main/java/org/openelisglobal/common/rest/provider/PatientSearchRestController.java
[Screencast from 25-07-24 16:14:06.webm](https://github.com/user-attachments/assets/42457efe-3655-4b4f-b46f-eab1c7f4ceb4)
> updated search functionality

- frontend/src/components/admin/reflexTests/ReflexStyles.css
- frontend/src/components/layout/search/searchBar.css
- frontend/src/components/layout/search/searchBar.js
- frontend/src/components/layout/search/searchService.js
> update  search bar to redirect to patient History

- src/main/java/org/openelisglobal/common/provider/query/LabOrderSearchProvider.java
- src/main/java/org/openelisglobal/dataexchange/fhir/service/FhirTransformServiceImpl.java
> incoming Order Location should be populated on Order Entry

- frontend/src/components/addOrder/Index.js
- frontend/src/components/eOrder/EOrder.js
- pom.xml
- src/main/java/org/openelisglobal/common/provider/query/LabOrderSearchProvider.java
- src/main/java/org/openelisglobal/common/rest/provider/PatientDashBoardProvider.java
- src/main/java/org/openelisglobal/dataexchange/order/dao/ElectronicOrderDAO.java
- src/main/java/org/openelisglobal/dataexchange/order/daoimpl/ElectronicOrderDAOImpl.java
- src/main/java/org/openelisglobal/dataexchange/service/order/ElectronicOrderService.java
- src/main/java/org/openelisglobal/dataexchange/service/order/ElectronicOrderServiceImpl.java
> FFix Loading NonConforming eOrders

- .github/workflows/frontend-qa.yml
- frontend/cypress.config.js
- frontend/cypress/e2e/batchOrderEntry.cy.js
- frontend/cypress/fixtures/BatchOrder.json
- frontend/cypress/pages/BatchOrderEntryPage.js
- frontend/cypress/pages/HomePage.js
- frontend/src/components/batchOrderEntry/SampleBatchEntry.js
https://github.com/user-attachments/assets/a4559865-0e83-4b90-adda-aea2f8cffc62
> E2E Coverage For Batch Order Entry

- .github/workflows/publish-and-test.yml
> fix CI build

- frontend/src/components/admin/Admin.js
- frontend/src/components/admin/BatchTestReassignmentAndCancellation/BatchTestReassignmentAndCancelation.js
- frontend/src/languages/en.json
- frontend/src/languages/fr.json
- src/main/java/org/openelisglobal/common/rest/provider/AllTestsForSampleTypeProviderRestController.java
- src/main/java/org/openelisglobal/common/rest/provider/PendingAnalysisForTestProviderRestController.java
- src/main/java/org/openelisglobal/test/controller/rest/BatchTestReassignmentRestController.java
- fixes #1158 
- reffercing #1051 
documentation.
- rewriting MVC controller to rest 
- JSP to React JS page
- 20% done WIP
Let me know if any changes are required :slightly_smiling_face: 
Thank You
> fix(batchTestReassignmentPage): Rewritting Batch test reassignment and cancelation JSP page to react Js

- src/main/java/org/openelisglobal/testreflex/action/util/TestReflexUtil.java
> fix broken reflexes for dictionary

- src/main/java/org/openelisglobal/testreflex/action/util/TestReflexUtil.java
> fix reflex

- pom.xml
Update of the version number to V3 Beta 1
> Tag V3 Beta 1

- src/main/java/org/openelisglobal/common/provider/query/LabOrderSearchProvider.java
- src/main/java/org/openelisglobal/dataexchange/fhir/FhirConfig.java
- src/main/java/org/openelisglobal/dataexchange/fhir/service/FhirApiWorkFlowServiceImpl.java
- src/main/java/org/openelisglobal/referral/fhir/service/FhirReferralServiceImpl.java
> Add suport for an asterisk when defining a remote source Identifier

- frontend/cypress.config.js
- frontend/cypress/pages/HomePage.js
- frontend/src/components/admin/Admin.js
- frontend/src/components/admin/generalConfig/common/ConfigMenuDisplay.js
- frontend/src/components/admin/generalConfig/common/GenericConfigEdit.js
- frontend/src/components/layout/Header.js
- frontend/src/components/reports/common/ReportByDate.js
- frontend/src/components/reports/common/ReportByID.js
- frontend/src/components/utils/Utils.js
- pom.xml
- src/main/java/org/openelisglobal/common/rest/DisplayListController.java
> Agg system roles end point and other minor fixes

- src/main/java/org/openelisglobal/notifications/rest/NotificationRestController.java
> Add Exception handling for push service

- src/main/java/org/openelisglobal/dataexchange/fhir/service/FhirApiWorkFlowServiceImpl.java
- volume/properties/common.properties
> add remote.poll.frequence property to the common properties

- src/main/java/org/openelisglobal/reports/action/implementation/PatientReport.java
> only reports with results should only print validated results

- frontend/cypress/e2e/report.cy.js
- frontend/src/components/formModel/innitialValues/PatientStatusReportFormValues.js
- frontend/src/components/home/Dashboard.tsx
- frontend/src/components/reports/auditTrailReport/AuditTrailReport.js
- frontend/src/components/reports/common/PatientStatusReport.js
- frontend/src/components/resultPage/SearchResultForm.js
- pom.xml
- src/main/java/org/openelisglobal/audittrail/action/workers/AuditTrailViewWorkerImpl.java
- src/main/webapp/pages/patient/patientManagement.jsp
> minor fixes for patient and audit report

- frontend/cypress/e2e/report.cy.js
- frontend/src/components/cytology/CytologyDashBoard.js
- frontend/src/components/home/Dashboard.tsx
- frontend/src/components/immunohistochemistry/ImmunohistochemistryDashboard.js
- frontend/src/components/pathology/PathologyDashboard.js
- frontend/src/components/patient/SearchPatientForm.js
- frontend/src/components/resultPage/SearchResultForm.js
- frontend/src/components/validation/SearchForm.js
- frontend/src/components/validation/Validation.js
- frontend/src/components/workplan/Workplan.js
- frontend/src/components/workplan/WorkplanSearchForm.js
> improve API pagination to display bundle page number

- frontend/src/components/admin/reflexTests/ReflexStyles.css
- ✅ The PR title includes a brief description of the work done, including the Issue number if applicable.
- ✅  The PR includes a video showing the changes for the work done.
- ✅  The PR title follows conventional commit label standards.
- ✅  The changes confirm to the OpenElis Global x3 Styleguide and design documentation.
- ✅  I have read and agree to the Contributing Guidelines of this project.
This pull request updates the `AutoComplete` component to ensure that the suggestion list dynamically adjusts its width based on the parent container, improving usability and consistency across different pages. 
Screen recording 
https://github.com/user-attachments/assets/de1a5ccd-9f80-4af9-9f41-5ea6c7c78bfe
Link to the related issue : https://github.com/I-TECH-UW/OpenELIS-Global-2/issues/1250
> Improve styling for the AutoComplete Component

- README.md
- dev.docker-compose.yml
- frontend/src/components/layout/search/searchBar.css
> update Read me and Global search bar styling
